language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - LARAVEL_VERSION=6.0.*
  - LARAVEL_VERSION=6.1.*
  - LARAVEL_VERSION=6.2.*
  - LARAVEL_VERSION=6.3.*

matrix:
  fast_finish: true
#  exclude:
#    - php: 7.0
#      env: LARAVEL_VERSION=5.6.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - composer update

script:
  - phpunit
